### ISSUE TITLE
Change the UI of permission_info.dart page [ Enhancement ]🧑‍💻

### ISSUE THREAD

**Issue by LOGESH-B** [LOGESH-B/SnapIt#1]
Hii Contributors
Make the permssion page looks cool

**Comment by AKASHANGADII** [comment]
Hey @LOGESH-B 
Is there any reference ui page available ?

**Comment by LOGESH-B** [comment]
Hii @AKASHANGADII 
No, Still there is no UI for this project
You want to make it looks good
